name: GitHub Actions Demo
on:
  issues:
    types: [opened]

jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v2
#       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."

  Test-Issue-Open:
    runs-on: ubuntu-latest
    steps:
      - run: echo "issue-name=${{ github.event.issue.title }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd && ls
      - name: Commit
        run: |
          echo "${{ github.event.issue.title }}" > README.md
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
