name: GitHub Actions Demo
on:
  issues:
    types: [opened]

jobs:
  Test-Issue-Open:
    runs-on: ubuntu-latest
    steps:
      - run: echo "issue-name=${{ github.event.issue.title }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Update README
        run: echo "${{ github.event.issue.title }}" >> README.md
      - name: Commit
        run: |
          git config --global user.name 'Chengqi Deng'
          git config --global user.email 'checkdeng0903@gmail.com'
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
